# Generated by Django 4.0.4 on 2022-05-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_bike_serial_number_bike_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='name',
            new_name='serialnumber',
        ),
    ]
