# Generated by Django 4.0.4 on 2022-05-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_reservation_bike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='biketype',
        ),
    ]
