# Generated by Django 4.0.4 on 2022-05-11 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_remove_bike_biketype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='biketype',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rental.biketype'),
            preserve_default=False,
        ),
    ]
